//
//  Sailing.swift
//  translator
//
//  Created by Patrick Renner on 28.03.24.
//

import Foundation

struct Sailing {
    
    var deen: [String: [String]] = [
        // test
//        "Abdrift (durch Strom/Wind)" : ["Leeway (current, wind)"],
//        "abfallen" : ["to bear away", "to fall off"],
//        "Ankerlaterne" : ["anchor light"],
//        "Ankerlicht" : ["anchor light"]

        "Abdrift (durch Strom/Wind)" : ["leeway (by current, wind)"],
        "abfallen" : ["to bear away", "to fall off"],
        "abflauen" : ["to becalm"],
        "ablandig" : ["offshore (from the shore coming)"],
        "abtreiben" : ["to drift"],
        "achteraus" : ["astern"],
        "Achterliek" : ["leech"],
        "achtern" : ["aft"],
        "Achtknoten" : ["figure of eight knot"],
        "am Wind" : ["close-hauled", "up-wind"],
        "Am-Wind Kurs" : ["close reach", "upwind"],
        "am Wind segeln" : ["to beat", "to sail on a close reach", "to sail upwind"],
        "an Deck" : ["on deck"],
        "anholen" : ["to sheet in"],
        "Anker aufholen" : ["to weigh anchor", "to raise the anchor"],
        "Anker hält" : ["anchor holds"],
        "Anker unklar" : ["anchor fouled"],
        "Anker werfen" : ["to drop anchor"],
        "Ankerkette" : ["anchor chain"],
        "Ankerlaterne" : ["anchor light"],
        "Ankerleine" : ["anchor warp"],
        "Ankerlicht" : ["anchor light"],
        "ankern" : ["to anchor"],
        "Ankerplatz" : ["anchorage"],
        "Ankerwinde" : ["windlass"],
        "Ankerwinsch" : ["anchor winch"],
        "Ankunftszeit (voraussichtlich)" : ["Estimated Time of Arrival (ETA)"],
        "Anlasser" : ["starter"],
        "anlegen" : ["to berth", "to dock", "to come alongside"],
        "anlegen Bug voraus" : ["to dock bows-to"],
        "anlegen Heck voraus" : ["to dock stern-to"],
        "Anlegestelle" : ["mooring place"],
        "anluven" : ["to come up", "to head up", "to luff up", "to go windward"],
        "auf Grund laufen" : ["to go aground"],
        "aufgelaufen" : ["aground"],
        "auflandig" : ["onshore (to the shore going)"],
        "aufschießen" : ["to go into the wind"],
        "aufschießen einer Leine" : ["to coil a line"],
        "Auftriebsweste" : ["buoyancy aid (BA)", "personal flotation device (PFD)"],
        "Auge (Leine)" : ["turn"],
        "aus der Klemme lösen" : ["to uncleat"],
        "Ausguck" : ["lookout"],
        "Auslaßventil" : ["exhaust valve", "outlet valve"],
        "Auspuff" : ["exhaust"],
        "ausrauschen" : ["to let go", "to sheet out quickly (unwanted)"],
        "ausreiten" : ["to hike out"],
        "Außenbordmotor" : ["outboard engine"],
        "Aussichten" : ["watch"],
        "Backbord": ["port (side)"],
        "Backbordbug": ["starboard tack (wind from starboard)"],
        "backhalten": ["to backwind"],
        "Backskiste": ["locker"],
        "Ballastkiel": ["ballast keel"],
        "Beiboot": ["dinghy"],
        "beidrehen": ["to heave to"],
        "beiliegen": ["to lie to", "to be hove to", "heaving to"],
        "beklemmen, belegen": ["to cleat off"],
        "belegen": ["to cleat"],
        "bergen": ["to lower a sail"],
        "Besatzungsliste": ["crew list"],
        "Betonnung": ["buoyage, beaconage"],
        "Bier": ["beer"],
        "Bilge": ["bilge"],
        "Bilgenpumpe": ["bilge pump"],
        "Bilgenwasser": ["bilge water"],
        "Bindereff": ["jiffy reef"],
        "Blink Feuer": ["long flashing light"],
        "Blitz Feuer": ["flashing light"],
        "Block": ["pulley", "block"],
        "Böe": ["gust", "squall"],
        "Bohle": ["plank"],
        "Boje": ["buoy"],
        "Bootshaken": ["boat hook"],
        "Bootsmanns Stuhl": ["bosun's chair", "harness"],
        "Bootspapiere": ["boat papers"],
        "Bordtoilette": ["heads, on bord toilette"],
        "Brecher": ["breakers"],
        "Breite (des Bootes)": ["beam"],
        "Breite (geographische)": ["latitude"],
        "Bucht": ["bay"],
        "Bug": ["bow", "front", "stem"],
        "Bugkorb": ["pulpit"],
        "Bugstrahlruder": ["bow thruster"],
        "Bullauge": ["porthole"],
        "Bullenstander": ["preventer", "gybe guard"],
        "Crewliste": ["crew list"],
        "Cunningham": ["cunningham"],
        "Curryklemme": ["camcleat", "jamming cleat"],
        "Dauerfeuer": ["fixed light"],
        "Deck": ["deck"],
        "Decksmann": ["deckhand"],
        "Deviation": ["deviation"],
        "dichtholen": ["to sheet in"],
        "Dichtung": ["gasket"],
        "Druck aus dem Segel nehmen": ["to depower a sail"],
        "Dunst": ["mist"],
        "Dünung": ["swell", "surge"],
        "Durchfahrtshöhe": ["clearance", "claering hight"],
        "durchrauschen": ["to slip through"],
        "Echolot": ["depth sounder, echo sounder"],
        "Eigner": ["owner of the boat"],
        "Eimer": ["bucket"],
        "Ein-Hand": ["single handed"],
        "eindampfen": ["to spring into line"],
        "Einlaßventil": ["intake valve"],
        "Fahrrinne": ["shipping channel", "fairway"],
        "Fahrwasser, Fahrrinne": ["channel"],
        "Fernglas": ["binoculars"],
        "Festfeuer": ["fixed light"],
        "festmachen": ["to moor up", "to tie-up a boat"],
        "Festmacher (-leine)": ["docking line", "mooring line"],
        "Feuerlöscher": ["fire extinguisher"],
        "fieren": ["to sheet out", "to ease the sheets", "to slack"],
        "Flachwasser": ["shoal waters", "shallow waters"],
        "Flaute (0 Bft)": ["calm (0 Bft)"],
        "Flügelrad": ["impeller"],
        "Freibord": ["freeboard"],
        "frische Brise (5 Bft)": ["fresh breeze (5 Bft)"],
        "Frischwassertank": ["fresh water tank"],
        "Funkelfeuer": ["quick light"],
        "Funkgerät": ["radio"],
        "Fußreling": ["toe rail"],
        "Gashebel": ["throttle"],
        "Gastflagge": ["courtesy flag"],
        "gegen den Wind": ["upwind", "against the wind"],
        "gegenwärtige Position": ["current position"],
        "Gegenwind": ["headwind"],
        "Gennaker": ["gennaker", "asymmetric spinnaker"],
        "Geografische Breite": ["latitude"],
        "Geografische Länge": ["longitude"],
        "GFK (Glasfaserverstärkter Kunsstoff)": ["GRP (glass-fibre reinforced plastic)"],
        "Gieren": ["to yaw", "yawing"],
        "Gleichtaktfeuer": ["Isophase"],
        "gleiten": ["to plane"],
        "Grauwassertank": ["gray water tank"],
        "Hafen": ["harbour", "port"],
        "Hafenmeister": ["harbour master"],
        "Hafenbüro": ["harbour office"],
        "Halbwind segeln": ["to reach", "to sail beam reach"],
        "Halbwindkurs": ["beam reach"],
        "halsen": ["to gybe"],
        "Handpeilkompass": ["handbearing compass"],
        "Havarie": ["accident"],
        "Heckkorb": ["pushpit"],
        "hoch am Wind / hart am Wind": ["close-hauled"],
        "hoch am Wind segeln": ["to sail close-hauled"],
        "Höhe (geographische)": ["altitude"],
        "Höhe kneifen": ["to pinch"],
        "im Päckchen liegen": ["to raft up"],
        "im Wind": ["head to wind", "no go zone"],
        "im Wind (stehengeblieben)": ["in irons"],
        "in den Wind gehen": ["to luff up", "to go into the wind"],
        "in Lee": ["leeward", "downwind"],
        "in Luv": ["windward", "upwind"],
        "instabil": ["tippy"],
        "kabbelig": ["choppy"],
        "Kabelbinder": ["cable tie", "zip tie"],
        "Kajüte (Kabine)": ["cabin"],
        "kardanisch aufhängen": ["to gimbal"],
        "Kartentisch": ["chart table"],
        "kentern": ["to capsize"],
        "Kenterung": ["capsize"],
        "Kettenkasten": ["chain locker"],
        "Kielbolzen": ["keel bolts"],
        "Kielboot": ["keel boat"],
        "killenendes Segel": ["luffing sail", "flapping sail"],
        "Klampe": ["cleat, horn cleat"],
        "Klemme": ["cleat"],
        "Knoten": ["knot", "hitch"],
        "Knoten (Geschwindigkeit)": ["knot (speed)"],
        "Koje": ["berth", "bunk"],
        "Kollision": ["collision"],
        "Kombüse": ["galley"],
        "Kompass": ["compass"],
        "Kopfschlag": ["locking turn"],
        "krängen": ["to heel"],
        "Krängung": ["heel"],
        "kreuzen": ["to beat (upwind)"],
        "Kreuzschlitz Schraubendreher": ["phillips screw driver"],
        "Kurbel": ["crank"],
        "Kurs": ["course"],
        "Küstenwache": ["coastguard"],
        "Landanschluss": ["shore power"],
        "Landwind": ["offshore wind"],
        "längsseits": ["alongside"],
        "Lateral Zeichen": ["channel marker"],
        "Lateralplan": ["lateral plan"],
        "Lattentasche": ["batten pocket"],
        "Laufplanke": ["plank", "gangway"],
        "Leck": ["leak"],
        "lecken": ["to leak"],
        "Lee vor Luv": ["windward gives way to leeward"],
        "leegierig": ["lee helm"],
        "leewärts, weg vom Wind": ["leeward side, downwind"],
        "leichte Brise (2 Bft)": ["light breeze (2 Bft)"],
        "Leinen los!": ["Cast off! Slip lines!"],
        "Leiser Zug (1 Bft)": ["light air (1 Bft)"],
        "lenzen": ["to bail"],
        "Lenzventil": ["draining hole"],
        "letzter Hafen": ["previous port of call"],
        "Leuchttonne": ["light buoy"],
        "Leuchtturm": ["light house"],
        "Liegeplatz": ["berth", "mooring"],
        "Logbuch": ["ship's logbook"],
        "Lot": ["echosounder"],
        "Luke": ["hatch"],
        "luvwärts, in Richtung Wind": ["windward"],
        "Mann über Bord": ["man overboard"],
        "Mannschaft": ["crew"],
        "Manöver": ["manoeuver"],
        "manövrieren": ["to manoeuvre"],
        "Marina": ["marina"],
        "mäßige Brise (4 Bft)": ["moderate breeze (4 Bft)"],
        "Mastbruch": ["dismasting"],
        "Mastwurf": ["clove hitch"],
        "mittschiffs": ["midship"],
        "Mole": ["pier"],
        "Mooringboje": ["mooring buoy"],
        "Navigationsbesteck": ["navigation tools"],
        "Niedergang": ["companionway"],
        "Niederholer": ["down haul", "cunningham"],
        "Niesel": ["drizzle"],
        "Notmast": ["jury mast, jury rigging"],
        "Notruder": ["jury rudder"],
        "Notsignal": ["distress signal"],
        "Oberlicht": ["skylight"],
        "Ölzeug": ["oilskin", "foul weather gear", "waterproofs"],
        "Opferanode": ["zinc anode", "zinc protector", "sacrificial anode"],
        "Orkan (12 Bft)": ["hurricane force (12 Bft)"],
        "orkanartiger Sturm (11 Bft)": ["violent storm (11 Bft)"],
        "Öse": ["loop, ring, tab, ear"],
        "Palstek": ["bowline"],
        "Pantry": ["galley"],
        "Panzertape": ["duct tape"],
        "Patenthalse": ["accidental gybe"],
        "peilen": ["to bear", "to take a bearing"],
        "Peilung": ["bearing"],
        "Persenning": ["cover"],
        "Planke": ["plank"],
        "platt vorm Wind": ["dead downwind"],
        "Plicht": ["cockpit"],
        "Poller": ["bollard"],
        "Positionslaternen": ["navigation lights"],
        "Positionslichter": ["navigation lights"],
        "Propeller": ["propeller, prop"],
        "Propellerwelle": ["propeller shaft"],
        "Pütz": ["bucket"],
        "querab": ["abeam, on the beam"],
        "Querleine": ["breast line"],
        "Radeffekt": ["prop(eller) walk"],
        "Raum!": ["water!"],
        "raumender Wind": ["backing wind"],
        "raumschots": ["reaching"],
        "Raumschotskurs": ["broad reach"],
        "Ree!": ["Lee-oh! (tack)"],
        "Reff": ["reef"],
        "Reffbändsel": ["reef lines"],
        "reffen": ["to reef"],
        "Reling": ["railing", "rail"],
        "Relingsstütze": ["stanchion"],
        "Rettungsboot": ["life boat"],
        "Rettungsinsel": ["liferaft"],
        "Rettungsweste": ["life jacket"],
        "Rigg": ["rigging"],
        "Rollfock": ["furling jib"],
        "Rollreff": ["furling reef"],
        "rückwärts fahren": ["to go astern"],
        "Ruder(blatt)": ["rudder (blade)"],
        "Rudergänger": ["helmsman"],
        "Rund Achtern!": ["Helm to Weather!, Gybe ho"],
        "Schäkel": ["shackle"],
        "Schäkelbolzen": ["clevis pin, shackle bolt"],
        "Schäkelschlüssel": ["shackle opener"],
        "Schalttafel": ["switch panel", "switch board"],
        "Schaumkronen": ["white horses", "white caps"],
        "scheinbarer Wind": ["apparent wind"],
        "Schiffsführer": ["skipper"],
        "schiften": ["to shift"],
        "Schlag": ["tack"],
        "Schlauch": ["hose"],
        "Schlauchboot": ["inflatable dinghy", "rubber raft", "rubber dinghy"],
        "Schleppleine": ["tow line"],
        "Schmetterling segeln": ["to goose wing"],
        "Schmutzwassertank": ["holding tank", "black water tank"],
        "Schnappschäkel": ["snap shackle"],
        "Schnelles Funkelfeuer": ["very quick light"],
        "Schot": ["sheet"],
        "Schothorn": ["clew"],
        "Schotstek": ["sheet bend"],
        "Schott": ["bulkhead"],
        "Schraube (Porpeller)": ["propeller, prop"],
        "schwache Brise (3 Bft)": ["gentle breeze (3 Bft)"],
        "schwerer Sturm (10 Bft)": ["storm, whole gale (10 Bft)"],
        "Schwert": ["centreboard, daggerboard"],
        "Schwimmhilfe": ["buoyancy aid (BA)", "personal flotation device (PFD)"],
        "Schwimmweste": ["life vest", "life jacket"],
        "Seebeine": ["sea legs"],
        "Seebrücke": ["pier"],
        "Seegang": ["sea state", "swell"],
        "Seekarte": ["chart", "nautical chart"],
        "seekrank sein": ["to be seasick"],
        "Seekrankheit": ["seasickness"],
        "Seemannschaft": ["crew, seafarer"],
        "Seemannsgarn": ["sailor's yarn", "shaggy dog story"],
        "Seemannsknoten": ["nautical knot", "salor's knot"],
        "Seemannstuhl": ["bosun's chair", "harness"],
        "Seemeile": ["nautical mile", "sea mile"],
        "Seenot": ["distress at sea"],
        "Seesack": ["duffel bag"],
        "Seeventil": ["seacock"],
        "Segel bergen": ["to drop/lower the sail"],
        "Segel fieren": ["to sheet out"],
        "Segel setzen": ["to set the sail", "to hoist a sail"],
        "Segel setzen, heissen": ["to hoist the sail"],
        "Segelfläche": ["sail area"],
        "Segelhandschuhe": ["sailing gloves"],
        "Segellatte": ["batten"],
        "Segeltörn": ["sailing tour", "cruise"],
        "Segeltrimm": ["sail trim"],
        "selbstholende Winsch": ["self-tailing winch"],
        "Sicherung (elektr.)": ["fuse, circut breakers"],
        "sinken": ["to sink"],
        "Smut": ["cook"],
        "Smutje": ["cook"],
        "Sonnenschuß": ["broach"],
        "Sorgleine": ["lifeline"],
        "Spiegel (am Heck)": ["transom"],
        "Sprayhood": ["dodger", "spray hood"],
        "Spühlen (Toilette)": ["flush"],
        "stampfen": ["to pitch"],
        "starker Wind (6 Bft)": ["strong breeze (6 Bft)"],
        "Steg": ["jetty", "pontoon"],
        "stehende Peilung": ["constant bearing"],
        "steifer Wind (7 Bft)": ["near gale, high wind, moderate gale (7 Bft)"],
        "Steuer": ["helm", "tiller", "steering wheel"],
        "Steuerbordbug": ["port tack (wind from port side)"],
        "Steuermann": ["helm, helmsman"],
        "steuern, am Ruder sein": ["to helm, to steer"],
        "Steuerrad": ["steering wheel"],
        "Stopperstek": ["rolling hitch"],
        "stranden": ["to strand"],
        "Sturm (9 Bft)": ["strong gale, severe gale (9 Bft)"],
        "Sturm (allgemein)": ["storm"],
        "stürmischer Wind (8 Bft)": ["gale, fresh gale (8 Bft)"],
        "Sturmwarnung": ["gale warning"],
        "Tampen": ["rope end"],
        "Tankstelle": ["fuel berth"],
        "Tau": ["rope"],
        "Tauwerk": ["rope", "lines", "ropeworks"],
        "Tiefgang": ["draft, draught"],
        "Toilette": ["heads, toilete"],
        "Tonne (Licht)": ["beacon, buoy, light"],
        "Törn (Windung)": ["turn"],
        "Traveller": ["traveller"],
        "Trimm": ["trim"],
        "trimmen": ["to trim"],
        "Überwasserschiff": ["surface ship"],
        "Umlenkblock": ["turning block", "pulley"],
        "unterbrochenes Feuer": ["occulting light"],
        "Unterbrochenes Funkelfeuer": ["interrupted quick light"],
        "Unterfeuer": ["front light, lower light"],
        "Unterliek": ["foot"],
        "Unterwasserschiff": ["underwater hull"],
        "Untiefe": ["shoal, sandbank"],
        "Verklicker": ["wind indicator"],
        "verstopft": ["clogged"],
        "vor dem Wind segeln": ["to run, to run (dead) before the wind"],
        "voraus": ["ahead"],
        "Vorliek": ["luff"],
        "Vorliekstrecker": ["downhaul, cunningham"],
        "Vorschiff": ["foredeck"],
        "Vorschoter": ["crew, foredeckhand, bowman"],
        "Vorschoter sein": ["to crew"],
        "Vorwind": ["run, before the wind, downwind"],
        "Wache": ["watch"],
        "wahrer Wind": ["true wind", "atmospheric wind"],
        "Wassertiefe": ["water depth", "soundings", "depth"],
        "Webeleinenstek": ["clove hitch"],
        "wenden": ["to go about", "to come about", "to tack"],
        "Windfähnchen (Fäden) am Segel": ["tell tales"],
        "Windloch": ["lull"],
        "Windstärke": ["wind force", "wind strength"],
        "Windsteueranlage": ["wind vane"],
        "Windstille (0 Bft)": ["calm (0 Bft)"],
        "Winsch": ["winch"],
        "Winschkurbel": ["winch handle"],
        "Zange": ["pliers"],
        "Zündkerze": ["spark plug"],
        "zurren": ["to lash"],
        ]

    var ende: [String: [String]] {
        var result = [String: [String]]()

        for key in self.deen.keys {
            let values = self.deen[key]
            for value in values! {
                if result[value] != nil {
                    var currentKeys: [String] = result[value]!
                    currentKeys.append(key)
                    result[value] = currentKeys
                } else {
                    result[value] = [key]
                }
            }
        }
        return result
        
        // first only
//        let e = Dictionary(deen.map({ ($1.first!, [$0]) }), uniquingKeysWith: {
//            (old, new) in old + new
//        })
//        return e
    }
    
}
